### ISSUE TITLE
Systers Community members want to know upcoming events.

### ISSUE THREAD

**Issue by ExactlyMay** [systers/communities#6] opened 2018-02-23 18:43 UTC
## Description
As a Systers Community member,
I need know the upcoming events,
so that I can learn how to engage.

## Mocks
- Initial Sketch
![paper-mockup-plan](https://user-images.githubusercontent.com/2440938/36611026-1e7b6dba-18a0-11e8-9516-126ea26bcc5c.jpg)
- Digital Mock
![balsamiq-mockup](https://user-images.githubusercontent.com/2440938/36610889-b822c11c-189f-11e8-9629-83238e1bd3fb.png)
[Link to Digital Mock](https://balsamiq.cloud/s2yi8tb/ppaxj1r)

### Google Calendar Integration [Required]
- [ ] Create a Mock Screen that follows AnitaB.org Branding Guidelines.
- [ ] Create a clear UML diagram or architecture that shows the interactions of this feature.
- [ ] Submit a PR that solves this issue and includes unit tests for this feature.
- [ ] Code review completed by 2 Systers Open Source members for the submitted PR.

### Enhancement to Calendar Integration [Optional]
- [ ] Add a mock for the 10 most current events displayed on the Home Page.
- [ ] Create a UML diagram to show the interactions from the initial Calendar integration to the Home Page.
- [ ] Submit a PR that displays the 10 most current events on the Home Page.
- [ ] Code review completed by 2 Systers Open Source members for this enhancement.

## Definition of Done
- [ ] All of the required items are completed. (Enhancements are optional.)
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by Saichethan** [comment] 2018-02-27 10:10
Can I work on this?
And are "GSoC", "2016", "Syster.io" dropdowns or tables
Please clarify this before I start working on this

**Comment by BaaniLeen** [comment] 2018-03-02 10:34
@MeepyMay @prachi1210 I would like to work on this issue. Can you please assign it to me, so that I can start working on the same! :)

**Comment by BaaniLeen** [comment] 2018-03-02 10:43
@Saichethan Shreya is already working on this! :)
You can start working on some other issue :)

**Comment by shreyateeza** [comment] 2018-03-02 10:59
Yes @Saichethan as Baani said I am working on this issue.

**Comment by Saichethan** [comment] 2018-03-02 14:11
@shreyateeza  Sure!

**Comment by BaaniLeen** [comment] 2018-03-04 14:18
![screen shot 2018-03-04 at 7 40 07 pm](https://user-images.githubusercontent.com/22029744/36946511-e89bd4c8-1fe3-11e8-835f-062e7863cb24.png)
@MeepyMay @prachi1210 Looking forward to your suggestions and feedback regarding the mock-ups :)
Shall I go ahead with the UML Diagram and architecture design?

**Comment by prachi1210** [comment] 2018-03-04 17:11
@BaaniLeen this looks good to me and line with the sketch by May, I have one question though did you use the colour scheme from the AnitaB.org Branding Guidelines?

**Comment by MeepyMay** [comment] 2018-03-05 17:41
To clarify, any student who is applying to GSoC can work on issues that are related to the "Project Ideas" of GSoC 2018.

@BaaniLeen This is an embedded calendar and that was specified on the Ideas List "No embedding." Can you include a menu as well? This can be a separate page from the Home Page, but it still is part of the "Systers Celebration" site.

One of the calendar samples I found was: [PigNose](https://www.pigno.se/barn/PIGNOSE-Calendar/)

**Comment by BaaniLeen** [comment] 2018-03-06 01:21
@MeepyMay Sorry! I missed that point!
@prachi1210 Will look into the same as well as the AnitaB.org Branding Guidelines once again, to create fresh mockups :)

**Comment by Saichethan** [comment] 2018-03-06 04:31
@MeepyMay  even [PIGNOSE-Calendar/](https://www.pigno.se/barn/PIGNOSE-Calendar/) this is not integrated with Google am I wrong? Correct me if I am.

**Comment by Saichethan** [comment] 2018-03-06 04:32
As of now I have only familiar with iframe or ical or integrating Google calendar so, if there is any other site using this would be helpful!

**Comment by MeepyMay** [comment] 2018-03-08 18:33
@Saichethan @BaaniLeen @shreyateeza Feel free to submit any mocks. This doesn't guarantee who completes this task. More so, it will give you an opportunity to add your contributions/designs to the second question under [GitHub Pages in the Systers GSoC application](https://docs.google.com/document/d/1mABPOVuuGO5TzxAsSV_9PKdkjyVRAr2js_-S43dhCaY/edit?usp=sharing).

**Comment by MeepyMay** [comment] 2018-03-08 18:40
@Saichethan Yes, it's not integrated. That's our current problem. I've been trying to pull event data from a Systers Google Calendar to populate a table on our site. I tried utilizing [this script](https://developers.google.com/google-apps/calendar/quickstart/nodejs) to get event data.

I googled Bootstrap calendars so we can display something that's integrated with our own design.

**Comment by Saichethan** [comment] 2018-03-09 02:45
@MeepyMay if you are thinking of compatibility on all devices please do check AMP instead of Bootstrap

**Comment by MeepyMay** [comment] 2018-03-12 23:15
@Saichethan AMP/Bootstrap/Node, anything goes. The goal is to accomplish this task, not to use a specific technology to solve it.

Before coding though, please submit mocks so we know what is getting coded.

**Comment by Saichethan** [comment] 2018-03-13 04:52
As, @MeepyMay you earlier suggested me not to start coding before coding period so, mock should be something in pdf or pain forms , I mean how can I show that I am capable of completing this task other than actually building it? Correct me if I am wrong?

**Comment by Tharangi** [comment] 2018-06-30 13:10
Duplicate of #36

**Closed** 2018-06-30 13:10 UTC
Labels: Category: Coding, Category: User Interface, Priority: HIGH, Program: GSoC
